### ISSUE TITLE
AfterShock XE

### ISSUE THREAD

**Issue by borg42** [pbrochart/oaunofficial#1]
Hi,

We are currently working on an AfterShock fork which we call "AfterShock XE". We intend to merge it back to the original AfterShock if we get the OK from the original developer.

You can find our git here: https://github.com/Irbyz/aftershock-xe

Unfortunately we didn't see your git before we started, so the code bases have diverged a little bit. Do you think it is feasible to merge your changes with ours so we can work on AfterShock together?

I think we shouldn't fragment the community any more. What do you think?

**Comment by borg42** [comment]
I just did a diff between our gits and it is not too bad. If you are OK with it i would go through the diff and pick all of the features that you did as well as the fixes that we don't yet have and make a commit out of it for the AfterShock XE git.

Not sure if there is a better way to merge it at this point?

**Comment by pbrochart** [comment]
Hi,

I'm agree and happy to know that other people are trying to do some nice stuffs.
Aftershock Mod is nice for CA but I think it needs improvements (CTF for example).
I work very slowly (2 releases in 6 months) because i have no much time and i don't want to break something so i need to understand how it works.

So yes if we can work together it will be nice.
Don't hesitate if you have a question.

**Comment by borg42** [comment]
Nice!

I will merge your changes into the AfterShock XE git tonight. Would be nice if you could then either fork it so it is easier for us to merge in the future or we could also give you commit rights to the git, then you could work on the git directly.

Whatever you would like better!

**Comment by borg42** [comment]
Alright, it is done!

I merged all of your changes into the AfterShock XE git. See here: https://github.com/Irbyz/aftershock-xe/commits/master

I tried to put your new features into logical commits so they are easier to separate from each other.

Thank you very much for you work!
